
syntax="proto3";

option optimize_for = LITE_RUNTIME;

import "google/protobuf/timestamp.proto";

enum OfficerSkillType {
  OFFICERSKILLTYPE_UNKNOWN = 0;
  OFFICERSKILLTYPE_ALWAYSON = 1;
  OFFICERSKILLTYPE_ONDUTY = 2;
  OFFICERSKILLTYPE_SELECTABLE = 3;
  OFFICERSKILLTYPE_ACTIVATEDABILITY = 4;
}

enum OfficerProgressType {
  OFFICERPROGRESSTYPE_UNKNOWN = 0;
  OFFICERPROGRESSTYPE_LEVELUP = 1;
  OFFICERPROGRESSTYPE_RANKUP = 2;
}

message CommanderSkillSpec {
  int64 researchId = 1;
  int32 groupId = 2;
  int32 sortOrder = 3;
  OfficerSkillType skillType = 4;
}

message OfficerLevelRewardsSpec {
  int32 amount = 1;
  int64 id = 2;
  int32 level = 3;
  string schemaId = 4;
}

message OfficerProgressRewardSpec {
  OfficerProgressType progressType = 1;
  int32 rank = 2;
  int32 schemaId = 3;
  repeated int32 amount = 4;
}
