#pragma once

#include "config.h"
#include "errormsg.h"

#include <il2cpp/il2cpp_helper.h>
#include <il2cpp/il2cpp-functions.h>
#include <spdlog/spdlog.h>

#include <cstring>
#include <filesystem>
#include <fstream>
#include <vector>

// Embedded image headers (auto-generated by xmake before_build)
#include "embedded_loading_image.h"
#include "embedded_logo_image.h"
#include "embedded_cc_logo_image.h"


namespace ls_common {

struct FakeRect { float x, y, width, height; };
struct FakeVector2 { float x, y; };
struct FakeVector3 { float x, y, z; };
struct FakeColor { float r, g, b, a; };

inline Il2CppObject* InvokeRuntime(const MethodInfo* method, void* target, void** args, const char* name)
{
  if (!method) return nullptr;
  Il2CppException* exception = nullptr;
  Il2CppObject*    result    = il2cpp_runtime_invoke(method, target, args, &exception);
  if (exception) {
    spdlog::warn("[LS] {} invocation failed", name);
    return nullptr;
  }
  return result;
}

inline bool InvokeVoid(const MethodInfo* method, void* target, void** args, const char* name)
{
  if (!method) return false;
  Il2CppException* exception = nullptr;
  il2cpp_runtime_invoke(method, target, args, &exception);
  if (exception) {
    spdlog::warn("[LS] {} invocation failed", name);
    return false;
  }
  return true;
}

inline bool InvokeBool(const MethodInfo* method, void* target, void** args, const char* name)
{
  Il2CppObject* result = InvokeRuntime(method, target, args, name);
  if (!result) return false;
  return *reinterpret_cast<bool*>(il2cpp_object_unbox(result));
}

inline int32_t InvokeInt32(const MethodInfo* method, void* target, int32_t fallback, const char* name)
{
  Il2CppObject* result = InvokeRuntime(method, target, nullptr, name);
  if (!result) return fallback;
  return *reinterpret_cast<int32_t*>(il2cpp_object_unbox(result));
}

inline void* InvokeObject(const MethodInfo* method, void* target, void** args, const char* name)
{
  return InvokeRuntime(method, target, args, name);
}

inline void SetFullRect(void* rt, FakeVector2 aMin, FakeVector2 aMax, FakeVector2 pivot, FakeVector2 sd, FakeVector2 ap)
{
  if (!rt) return;
  static auto rt_h  = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "RectTransform");
  static auto fn_am = rt_h.GetMethodInfo("set_anchorMin");
  static auto fn_ax = rt_h.GetMethodInfo("set_anchorMax");
  static auto fn_pv = rt_h.GetMethodInfo("set_pivot");
  static auto fn_sd = rt_h.GetMethodInfo("set_sizeDelta");
  static auto fn_ap = rt_h.GetMethodInfo("set_anchoredPosition");
  if (!fn_am || !fn_ax || !fn_pv || !fn_sd || !fn_ap) return;
  void* amA[1] = {&aMin};
  void* axA[1] = {&aMax};
  void* pvA[1] = {&pivot};
  void* sdA[1] = {&sd};
  void* apA[1] = {&ap};
  InvokeVoid(fn_am, rt, amA, "RT.set_anchorMin");
  InvokeVoid(fn_ax, rt, axA, "RT.set_anchorMax");
  InvokeVoid(fn_pv, rt, pvA, "RT.set_pivot");
  InvokeVoid(fn_sd, rt, sdA, "RT.set_sizeDelta");
  InvokeVoid(fn_ap, rt, apA, "RT.set_anchoredPosition");
}

inline void GetTextureSize(void* tex, int32_t& w, int32_t& h, int32_t fallbackW, int32_t fallbackH)
{
  static auto tex_h = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Texture2D");
  static auto fn_w  = tex_h.GetMethodInfo("get_width");
  static auto fn_h  = tex_h.GetMethodInfo("get_height");
  w = InvokeInt32(fn_w, tex, fallbackW, "Texture2D.get_width");
  h = InvokeInt32(fn_h, tex, fallbackH, "Texture2D.get_height");
}

inline void* CreateSpriteFromTexture(void* tex, int32_t fallbackW, int32_t fallbackH)
{
  if (!tex) return nullptr;
  static auto spr_h  = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Sprite");
  static auto fn_cre = spr_h.GetMethodInfo("Create", 3);
  if (!fn_cre) return nullptr;
  int32_t w, h;
  GetTextureSize(tex, w, h, fallbackW, fallbackH);
  FakeRect    rect{0.0f, 0.0f, (float)w, (float)h};
  FakeVector2 pivot{0.5f, 0.5f};
  void*       args[3] = {tex, &rect, &pivot};
  return InvokeObject(fn_cre, nullptr, args, "Sprite.Create");
}

inline void ConfigureImageSprite(void* imgComp, void* spr, bool preserveAspect)
{
  if (!imgComp) return;
  static auto img_h  = il2cpp_get_class_helper("UnityEngine.UI", "UnityEngine.UI", "Image");
  static auto fn_spr = img_h.GetMethodInfo("set_sprite");
  static auto fn_col = img_h.GetMethodInfo("set_color");
  static auto fn_typ = img_h.GetMethodInfo("set_type");
  static auto fn_asp = img_h.GetMethodInfo("set_preserveAspect");
  static auto fn_ray = img_h.GetMethodInfo("set_raycastTarget");
  void*       sprArgs[1] = {spr};
  InvokeVoid(fn_spr, imgComp, sprArgs, "Image.set_sprite");
  FakeColor white{1.0f, 1.0f, 1.0f, 1.0f};
  void*     colArgs[1] = {&white};
  InvokeVoid(fn_col, imgComp, colArgs, "Image.set_color");
  int32_t simple     = 0;
  void*   typArgs[1] = {&simple};
  InvokeVoid(fn_typ, imgComp, typArgs, "Image.set_type");
  void* aspArgs[1] = {&preserveAspect};
  InvokeVoid(fn_asp, imgComp, aspArgs, "Image.set_preserveAspect");
  if (fn_ray) {
    bool  rayOff    = false;
    void* rayArgs[1] = {&rayOff};
    InvokeVoid(fn_ray, imgComp, rayArgs, "Image.set_raycastTarget(false)");
  }
}

inline void HideImage(void* imgComp)
{
  if (!imgComp) return;
  static auto img_h  = il2cpp_get_class_helper("UnityEngine.UI", "UnityEngine.UI", "Image");
  static auto fn_col = img_h.GetMethodInfo("set_color");
  FakeColor   clear{0.0f, 0.0f, 0.0f, 0.0f};
  void*       args[1] = {&clear};
  InvokeVoid(fn_col, imgComp, args, "Image.set_color (transparent)");
}

inline void SafeDestroy(void* obj)
{
  if (!obj) return;
  try {
    static auto obj_h      = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Object");
    static auto fn_destroy = obj_h.GetMethodInfo("Destroy", 1);
    if (fn_destroy) {
      void* args[1] = {obj};
      InvokeVoid(fn_destroy, nullptr, args, "Object.Destroy");
    }
  } catch (...) {}
}

inline void ReadIl2CppString(void* strObj, char* buf, int bufSize)
{
  buf[0] = '\0';
  if (!strObj || bufSize <= 1) return;
  const auto* chars = reinterpret_cast<const char16_t*>((ptrdiff_t)strObj + 0x14);
  int         i     = 0;
  for (; i < bufSize - 1 && chars[i]; ++i)
    buf[i] = static_cast<char>(chars[i]);
  buf[i] = '\0';
}

inline void* FindRootCanvas(void* parentTransform)
{
  static auto go_h     = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "GameObject");
  static auto tr_h     = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Transform");
  static auto canvas_h = il2cpp_get_class_helper("UnityEngine.UIModule", "UnityEngine", "Canvas");
  static auto fn_get_parent = tr_h.GetMethod("get_parent");
  static auto fn_get_go     = tr_h.GetMethod("get_gameObject");
  static auto fn_gc_go      = go_h.GetMethod("GetComponent", 1);
  void*       canvasType    = canvas_h.GetType();

  void* cur = parentTransform;
  while (cur) {
    void* curGO = fn_get_go ? reinterpret_cast<void* (*)(void*)>(fn_get_go)(cur) : nullptr;
    if (curGO && fn_gc_go && canvasType) {
      if (reinterpret_cast<void* (*)(void*, void*)>(fn_gc_go)(curGO, canvasType))
        return cur;
    }
    cur = fn_get_parent ? reinterpret_cast<void* (*)(void*)>(fn_get_parent)(cur) : nullptr;
  }
  return parentTransform;
}

inline void* LoadTextureFromBytes(const uint8_t* data, size_t size)
{
  if (!data || size == 0) return nullptr;
  static auto tex_h   = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Texture2D");
  static auto conv_h  = il2cpp_get_class_helper("UnityEngine.ImageConversionModule", "UnityEngine", "ImageConversion");
  static auto fn_load = conv_h.GetMethodInfoSpecial("LoadImage", [](int param_count, const Il2CppType** param) {
    return param_count == 3 && param[1]->type == IL2CPP_TYPE_SZARRAY && param[2]->type == IL2CPP_TYPE_BOOLEAN;
  });
  if (!tex_h.isValidHelper() || !fn_load) return nullptr;
  static auto  byte_h = il2cpp_get_class_helper("mscorlib", "System", "Byte");
  Il2CppArray* arr    = il2cpp_array_new(byte_h.get_cls(), size);
  if (!arr) return nullptr;
  std::memcpy(((Il2CppArraySize*)arr)->vector, data, size);
  void* tex = il2cpp_object_new(tex_h.get_cls());
  if (!tex) return nullptr;
  static auto ctor = tex_h.GetMethodInfoSpecial(".ctor", [](int param_count, const Il2CppType** param) {
    return param_count == 4 && param[3]->type == IL2CPP_TYPE_BOOLEAN;
  });
  if (ctor) {
    int32_t width = 2, height = 2, textureFormat = 4;
    bool    mipChain    = false;
    void*   ctorArgs[4] = {&width, &height, &textureFormat, &mipChain};
    if (!InvokeVoid(ctor, tex, ctorArgs, "Texture2D.ctor"))
      return nullptr;
  }
  bool  markNonReadable = false;
  void* loadArgs[3]     = {tex, arr, &markNonReadable};
  return InvokeBool(fn_load, nullptr, loadArgs, "ImageConversion.LoadImage") ? tex : nullptr;
}

// --- Texture management (shared state) ---

inline void*& LoadingTextureRef()
{
  static void* texture = nullptr;
  return texture;
}

inline void*& LogoTextureRef()
{
  static void* texture = nullptr;
  return texture;
}

inline void*& CCLogoTextureRef()
{
  static void* texture = nullptr;
  return texture;
}

inline void* GetLoadingTexture()
{
  void*& texture = LoadingTextureRef();
  if (texture) return texture;
  const std::string& path = Config::Get().loader_image;
  if (!path.empty() && std::filesystem::exists(path)) {
    std::ifstream f(path, std::ios::binary);
    if (f.is_open()) {
      std::vector<uint8_t> data(std::istreambuf_iterator<char>(f), {});
      if (!data.empty())
        texture = LoadTextureFromBytes(data.data(), data.size());
    }
  }
  if (!texture)
    texture = LoadTextureFromBytes(g_embeddedLoadingImage, g_embeddedLoadingImage_SIZE);
  return texture;
}

inline void* GetLogoTexture()
{
  void*& texture = LogoTextureRef();
  if (!texture) {
    texture = LoadTextureFromBytes(g_embeddedLogoImage, g_embeddedLogoImage_SIZE);
  }
  return texture;
}

inline void* GetCCLogoTexture()
{
  void*& texture = CCLogoTextureRef();
  if (!texture) {
    texture = LoadTextureFromBytes(g_embeddedCCLogoImage, g_embeddedCCLogoImage_SIZE);
  }
  return texture;
}

inline void ResetTexturesForReload()
{
  LoadingTextureRef() = nullptr;
  LogoTextureRef()    = nullptr;
  CCLogoTextureRef()  = nullptr;
}

inline void* CreateImageOverlay(const char* name, void* texture, void* parentTransform, FakeVector2 aMin,
                                FakeVector2 aMax, FakeVector2 pivot, FakeVector2 sd, FakeVector2 ap,
                                bool preserveAspect, bool placeAsFirstSibling, int32_t fallbackW, int32_t fallbackH)
{
  if (!texture || !parentTransform) return nullptr;

  static auto go_h  = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "GameObject");
  static auto rt_h  = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "RectTransform");
  static auto tr_h  = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Transform");
  static auto img_h = il2cpp_get_class_helper("UnityEngine.UI", "UnityEngine.UI", "Image");

  static auto fn_go_ctor = go_h.GetMethodInfoSpecial(".ctor", [](int n, const Il2CppType** p) {
    return n == 1 && p[0]->type == IL2CPP_TYPE_STRING;
  });
  static auto fn_get_tr  = go_h.GetMethodInfo("get_transform");
  static auto fn_setpar  = tr_h.GetMethodInfoSpecial("SetParent", [](int n, const Il2CppType**) { return n == 2; });
  static auto fn_setfst  = tr_h.GetMethodInfo("SetAsFirstSibling");
  static auto fn_addcomp = go_h.GetMethodInfo("AddComponent", 1);
  static auto fn_gc      = go_h.GetMethodInfo("GetComponent", 1);
  if (!fn_go_ctor || !fn_get_tr || !fn_setpar || !fn_addcomp || !fn_gc) return nullptr;

  void* spr = CreateSpriteFromTexture(texture, fallbackW, fallbackH);
  if (!spr) return nullptr;

  void* go = il2cpp_object_new(go_h.get_cls());
  if (!go) return nullptr;
  void* nameStr   = il2cpp_string_new(name);
  void* goArgs[1] = {nameStr};
  if (!InvokeVoid(fn_go_ctor, go, goArgs, "GameObject.ctor")) return nullptr;

  void* tr = InvokeObject(fn_get_tr, go, nullptr, "get_transform");
  if (!tr) return nullptr;
  bool  worldStays = false;
  void* parArgs[2] = {FindRootCanvas(parentTransform), &worldStays};
  InvokeVoid(fn_setpar, tr, parArgs, "Transform.SetParent");
  if (placeAsFirstSibling && fn_setfst)
    InvokeVoid(fn_setfst, tr, nullptr, "Transform.SetAsFirstSibling");

  void* imgType   = img_h.GetType();
  void* acArgs[1] = {imgType};
  void* imgComp   = InvokeObject(fn_addcomp, go, acArgs, "AddComponent<Image>");

  void* rtType    = rt_h.GetType();
  void* rtArgs[1] = {rtType};
  void* rt        = InvokeObject(fn_gc, go, rtArgs, "GetComponent<RectTransform>");
  SetFullRect(rt, aMin, aMax, pivot, sd, ap);

  ConfigureImageSprite(imgComp, spr, preserveAspect);
  return go;
}

inline void CreateLogoOverlayEx(const char* name, void* texture, void* parentTransform, void*& outGO, float xSide)
{
  if (outGO) return;
  try {
    if (!texture || !parentTransform) return;

    constexpr float kRefScreenWidth = 1920.0f;
    constexpr float kRefLogoWidth   = 150.0f;
    constexpr float kRefPadX        = 30.0f;
    constexpr float kRefPadY        = 185.0f;

    static auto screen_h = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Screen");
    static auto fn_sw    = screen_h.GetMethodInfo("get_width");
    static auto fn_sh    = screen_h.GetMethodInfo("get_height");
    float       sw       = (float)(fn_sw ? InvokeInt32(fn_sw, nullptr, 0, "Screen.get_width") : 0);
    float       sh       = (float)(fn_sh ? InvokeInt32(fn_sh, nullptr, 0, "Screen.get_height") : 0);
    if (sw <= 0.0f) sw = 1334.0f;
    if (sh <= 0.0f) sh = 750.0f;

    float scale = (sw / kRefScreenWidth) * Config::Get().loader_logo_scale;

    int32_t lw, lh;
    GetTextureSize(texture, lw, lh, 256, 256);
    float logoWidth = kRefLogoWidth * scale;
    float logoPixH  = logoWidth * ((lw > 0) ? (float)lh / (float)lw : 1.0f);
    float padX      = kRefPadX * scale;
    float padY      = kRefPadY * scale;

    FakeVector2 aMin, aMax;
    if (xSide < 0.0f) {
      aMin = {padX / sw, padY / sh};
      aMax = {(padX + logoWidth) / sw, (padY + logoPixH) / sh};
    } else {
      aMin = {(sw - padX - logoWidth) / sw, padY / sh};
      aMax = {(sw - padX) / sw, (padY + logoPixH) / sh};
    }

    outGO = CreateImageOverlay(name, texture, parentTransform, aMin, aMax,
                               {0.5f, 0.5f}, {0.0f, 0.0f}, {0.0f, 0.0f},
                               true, false, 256, 256);
  } catch (...) {}
}

inline void CreateLogoOverlay(void* parentTransform, void*& logoGO)
{
  CreateLogoOverlayEx("STFCModLogo", GetLogoTexture(), parentTransform, logoGO, 1.0f);
}

inline void CreateCCLogoOverlay(void* parentTransform, void*& ccLogoGO)
{
  CreateLogoOverlayEx("STFCCCLogo", GetCCLogoTexture(), parentTransform, ccLogoGO, -1.0f);
}

inline void ApplySpriteToImage(void* imageComp, void* texture)
{
  if (!imageComp || !texture) return;
  void* spr = CreateSpriteFromTexture(texture, 792, 450);
  if (!spr) return;
  static auto img_h  = il2cpp_get_class_helper("UnityEngine.UI", "UnityEngine.UI", "Image");
  static auto fn_ovr = img_h.GetMethodInfo("set_overrideSprite");
  static auto fn_drt = img_h.GetMethodInfo("SetVerticesDirty");
  void*       sprArgs[1] = {spr};
  InvokeVoid(fn_ovr, imageComp, sprArgs, "Image.set_overrideSprite");
  ConfigureImageSprite(imageComp, spr, false);
  InvokeVoid(fn_drt, imageComp, nullptr, "Graphic.SetVerticesDirty");
}

inline void* CreateBGOverlay(void* parentTransform, void* texture)
{
  return CreateImageOverlay("STFCModBG", texture, parentTransform,
                            {0.0f, 0.0f}, {1.0f, 1.0f}, {0.5f, 0.5f},
                            {0.0f, 0.0f}, {0.0f, 0.0f}, false,
                            true, 792, 450);
}

} // namespace ls_common
