#pragma once

#include "config.h"
#include "errormsg.h"

#include <il2cpp/il2cpp_helper.h>
#include <il2cpp/il2cpp-functions.h>
#include <spdlog/spdlog.h>

#include <cstring>
#include <filesystem>
#include <fstream>
#include <vector>

// Embedded image headers (auto-generated by xmake before_build)
#include "embedded_loading_image.h"
#include "embedded_logo_image.h"
#include "embedded_cc_logo_image.h"


namespace ls_common {

struct FakeRect { float x, y, width, height; };
struct FakeVector2 { float x, y; };
struct FakeVector3 { float x, y, z; };
struct FakeColor { float r, g, b, a; };

inline Il2CppObject* InvokeRuntime(const MethodInfo* method, void* target, void** args, const char* name)
{
  if (!method) return nullptr;
  Il2CppException* exception = nullptr;
  Il2CppObject*    result    = il2cpp_runtime_invoke(method, target, args, &exception);
  if (exception) {
    spdlog::warn("[LS] {} invocation failed", name);
    return nullptr;
  }
  return result;
}

inline bool InvokeVoid(const MethodInfo* method, void* target, void** args, const char* name)
{
  if (!method) return false;
  Il2CppException* exception = nullptr;
  il2cpp_runtime_invoke(method, target, args, &exception);
  if (exception) {
    spdlog::warn("[LS] {} invocation failed", name);
    return false;
  }
  return true;
}

inline bool InvokeBool(const MethodInfo* method, void* target, void** args, const char* name)
{
  Il2CppObject* result = InvokeRuntime(method, target, args, name);
  if (!result) return false;
  void* value = il2cpp_object_unbox(result);
  return value ? *reinterpret_cast<bool*>(value) : false;
}

inline int32_t InvokeInt32(const MethodInfo* method, void* target, int32_t fallback, const char* name)
{
  Il2CppObject* result = InvokeRuntime(method, target, nullptr, name);
  if (!result) return fallback;
  void* value = il2cpp_object_unbox(result);
  return value ? *reinterpret_cast<int32_t*>(value) : fallback;
}

inline void* InvokeObject(const MethodInfo* method, void* target, void** args, const char* name)
{
  return InvokeRuntime(method, target, args, name);
}

inline void SetFullRect(void* rt, FakeVector2 aMin, FakeVector2 aMax, FakeVector2 pivot, FakeVector2 sd, FakeVector2 ap)
{
  if (!rt) return;
  static auto rt_h  = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "RectTransform");
  static auto fn_am = rt_h.GetMethodInfo("set_anchorMin");
  static auto fn_ax = rt_h.GetMethodInfo("set_anchorMax");
  static auto fn_pv = rt_h.GetMethodInfo("set_pivot");
  static auto fn_sd = rt_h.GetMethodInfo("set_sizeDelta");
  static auto fn_ap = rt_h.GetMethodInfo("set_anchoredPosition");
  if (!fn_am || !fn_ax || !fn_pv || !fn_sd || !fn_ap) return;
  void* amA[1] = {&aMin};
  void* axA[1] = {&aMax};
  void* pvA[1] = {&pivot};
  void* sdA[1] = {&sd};
  void* apA[1] = {&ap};
  InvokeVoid(fn_am, rt, amA, "RT.set_anchorMin");
  InvokeVoid(fn_ax, rt, axA, "RT.set_anchorMax");
  InvokeVoid(fn_pv, rt, pvA, "RT.set_pivot");
  InvokeVoid(fn_sd, rt, sdA, "RT.set_sizeDelta");
  InvokeVoid(fn_ap, rt, apA, "RT.set_anchoredPosition");
}

inline void* CreateSpriteFromTexture(void* tex, int32_t width, int32_t height)
{
  if (!tex || width <= 0 || height <= 0) return nullptr;
  static auto spr_h  = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Sprite");
  static auto fn_cre = spr_h.GetMethodInfo("Create", 3);
  if (!fn_cre) return nullptr;
  FakeRect    rect{0.0f, 0.0f, static_cast<float>(width), static_cast<float>(height)};
  FakeVector2 pivot{0.5f, 0.5f};
  void*       args[3] = {tex, &rect, &pivot};
  return InvokeObject(fn_cre, nullptr, args, "Sprite.Create");
}

inline bool ConfigureImageSprite(void* imgComp, void* spr, bool preserveAspect)
{
  if (!imgComp || !spr) return false;
  static auto img_h  = il2cpp_get_class_helper("UnityEngine.UI", "UnityEngine.UI", "Image");
  static auto fn_spr = img_h.GetMethodInfo("set_sprite");
  static auto fn_col = img_h.GetMethodInfo("set_color");
  static auto fn_typ = img_h.GetMethodInfo("set_type");
  static auto fn_asp = img_h.GetMethodInfo("set_preserveAspect");
  static auto fn_ray = img_h.GetMethodInfo("set_raycastTarget");
  if (!fn_spr || !fn_col || !fn_typ || !fn_asp) return false;

  bool        ok         = true;
  void*       sprArgs[1] = {spr};
  ok &= InvokeVoid(fn_spr, imgComp, sprArgs, "Image.set_sprite");
  FakeColor white{1.0f, 1.0f, 1.0f, 1.0f};
  void*     colArgs[1] = {&white};
  ok &= InvokeVoid(fn_col, imgComp, colArgs, "Image.set_color");
  int32_t simple     = 0;
  void*   typArgs[1] = {&simple};
  ok &= InvokeVoid(fn_typ, imgComp, typArgs, "Image.set_type");
  void* aspArgs[1] = {&preserveAspect};
  ok &= InvokeVoid(fn_asp, imgComp, aspArgs, "Image.set_preserveAspect");
  if (fn_ray) {
    bool  rayOff    = false;
    void* rayArgs[1] = {&rayOff};
    ok &= InvokeVoid(fn_ray, imgComp, rayArgs, "Image.set_raycastTarget(false)");
  }
  return ok;
}

inline void HideImage(void* imgComp)
{
  if (!imgComp) return;
  static auto img_h  = il2cpp_get_class_helper("UnityEngine.UI", "UnityEngine.UI", "Image");
  static auto fn_col = img_h.GetMethodInfo("set_color");
  FakeColor   clear{0.0f, 0.0f, 0.0f, 0.0f};
  void*       args[1] = {&clear};
  InvokeVoid(fn_col, imgComp, args, "Image.set_color (transparent)");
}

inline void SafeDestroy(void* obj)
{
  if (!obj) return;
  try {
    static auto obj_h      = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Object");
    static auto fn_destroy = obj_h.GetMethodInfo("Destroy", 1);
    if (fn_destroy) {
      void* args[1] = {obj};
      InvokeVoid(fn_destroy, nullptr, args, "Object.Destroy");
    }
  } catch (...) {}
}

inline void ReadIl2CppString(void* strObj, char* buf, int bufSize)
{
  buf[0] = '\0';
  if (!strObj || bufSize <= 1) return;
  const auto* chars = reinterpret_cast<const char16_t*>((ptrdiff_t)strObj + 0x14);
  int         i     = 0;
  for (; i < bufSize - 1 && chars[i]; ++i)
    buf[i] = static_cast<char>(chars[i]);
  buf[i] = '\0';
}

inline void* FindRootCanvas(void* parentTransform)
{
  static auto go_h     = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "GameObject");
  static auto tr_h     = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Transform");
  static auto canvas_h = il2cpp_get_class_helper("UnityEngine.UIModule", "UnityEngine", "Canvas");
  static auto fn_get_parent = tr_h.GetMethod("get_parent");
  static auto fn_get_go     = tr_h.GetMethod("get_gameObject");
  static auto fn_gc_go      = go_h.GetMethod("GetComponent", 1);
  void*       canvasType    = canvas_h.GetType();

  void* cur = parentTransform;
  while (cur) {
    void* curGO = fn_get_go ? reinterpret_cast<void* (*)(void*)>(fn_get_go)(cur) : nullptr;
    if (curGO && fn_gc_go && canvasType) {
      if (reinterpret_cast<void* (*)(void*, void*)>(fn_gc_go)(curGO, canvasType))
        return cur;
    }
    cur = fn_get_parent ? reinterpret_cast<void* (*)(void*)>(fn_get_parent)(cur) : nullptr;
  }
  return parentTransform;
}

inline Il2CppGCHandle LoadTextureFromBytes(const uint8_t* data, size_t size)
{
  if (!data || size == 0) return nullptr;
  static auto tex_h   = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Texture2D");
  static auto conv_h  = il2cpp_get_class_helper("UnityEngine.ImageConversionModule", "UnityEngine", "ImageConversion");
  static auto fn_load = conv_h.GetMethodInfoSpecial("LoadImage", [](int param_count, const Il2CppType** param) {
    return param_count == 3 && param[1]->type == IL2CPP_TYPE_SZARRAY && param[2]->type == IL2CPP_TYPE_BOOLEAN;
  });
  if (!tex_h.isValidHelper() || !fn_load) return nullptr;

  static auto  byte_h = il2cpp_get_class_helper("mscorlib", "System", "Byte");
  Il2CppArray* arr    = il2cpp_array_new(byte_h.get_cls(), size);
  if (!arr) return nullptr;
  std::memcpy(((Il2CppArraySize*)arr)->vector, data, size);

  auto* tex = il2cpp_object_new(tex_h.get_cls());
  if (!tex) return nullptr;

  // Root both managed objects before invoking Unity; native local pointers are
  // not sufficient roots if an invocation triggers a collection.
  Il2CppGCHandle bytes_handle   = il2cpp_gchandle_new(reinterpret_cast<Il2CppObject*>(arr), false);
  Il2CppGCHandle texture_handle = il2cpp_gchandle_new(tex, false);
  if (!bytes_handle || !texture_handle) {
    if (bytes_handle) il2cpp_gchandle_free(bytes_handle);
    if (texture_handle) il2cpp_gchandle_free(texture_handle);
    return nullptr;
  }

  static auto ctor = tex_h.GetMethodInfoSpecial(".ctor", [](int param_count, const Il2CppType** param) {
    return param_count == 4 && param[3]->type == IL2CPP_TYPE_BOOLEAN;
  });
  if (ctor) {
    int32_t width = 2, height = 2, textureFormat = 4;
    bool    mipChain    = false;
    void*   ctorArgs[4] = {&width, &height, &textureFormat, &mipChain};
    if (!InvokeVoid(ctor, il2cpp_gchandle_get_target(texture_handle), ctorArgs, "Texture2D.ctor")) {
      il2cpp_gchandle_free(bytes_handle);
      il2cpp_gchandle_free(texture_handle);
      return nullptr;
    }
  }

  bool  markNonReadable = false;
  void* loadArgs[3]     = {il2cpp_gchandle_get_target(texture_handle), il2cpp_gchandle_get_target(bytes_handle),
                           &markNonReadable};
  const bool loaded = InvokeBool(fn_load, nullptr, loadArgs, "ImageConversion.LoadImage");
  il2cpp_gchandle_free(bytes_handle);
  if (!loaded) {
    il2cpp_gchandle_free(texture_handle);
    return nullptr;
  }
  return texture_handle;
}

// --- Texture management (shared state) ---

inline uint32_t ReadBigEndian32(const uint8_t* value)
{
  return (static_cast<uint32_t>(value[0]) << 24) | (static_cast<uint32_t>(value[1]) << 16)
         | (static_cast<uint32_t>(value[2]) << 8) | static_cast<uint32_t>(value[3]);
}

inline bool ReadPngDimensions(const uint8_t* data, size_t size, int32_t& width, int32_t& height)
{
  static constexpr uint8_t png_signature[] = {0x89, 'P', 'N', 'G', 0x0D, 0x0A, 0x1A, 0x0A};
  if (!data || size < 24 || std::memcmp(data, png_signature, sizeof(png_signature)) != 0
      || std::memcmp(data + 12, "IHDR", 4) != 0) {
    return false;
  }

  const auto parsed_width  = ReadBigEndian32(data + 16);
  const auto parsed_height = ReadBigEndian32(data + 20);
  if (parsed_width == 0 || parsed_height == 0 || parsed_width > INT32_MAX || parsed_height > INT32_MAX) {
    return false;
  }

  width  = static_cast<int32_t>(parsed_width);
  height = static_cast<int32_t>(parsed_height);
  return true;
}

// Loading assets live for one LoginSequence generation. Strong handles keep
// the managed wrappers reachable while that generation is active; the next
// LoginSequence releases them and creates fresh Unity native resources.
class RootedImageAsset final
{
public:
  [[nodiscard]] bool Load(const uint8_t* data, size_t size, int32_t fallback_width, int32_t fallback_height,
                          const char* name)
  {
    if (Texture()) return true;

    width_  = fallback_width;
    height_ = fallback_height;
    if (!ReadPngDimensions(data, size, width_, height_)) {
      spdlog::warn("[LS] {} is not a supported PNG; using fallback dimensions {}x{}", name, width_, height_);
    }

    texture_handle_ = LoadTextureFromBytes(data, size);
    if (!texture_handle_) {
      spdlog::warn("[LS] failed to load and root {} texture", name);
      return false;
    }
    name_ = name;
    spdlog::debug("[LS] loaded and rooted {} texture ({}x{})", name_, width_, height_);
    return true;
  }

  [[nodiscard]] void* Texture() const
  {
    return texture_handle_ ? il2cpp_gchandle_get_target(texture_handle_) : nullptr;
  }

  [[nodiscard]] void* Sprite()
  {
    if (sprite_handle_) return il2cpp_gchandle_get_target(sprite_handle_);

    void* texture = Texture();
    if (!texture) return nullptr;
    auto* sprite = reinterpret_cast<Il2CppObject*>(CreateSpriteFromTexture(texture, width_, height_));
    if (!sprite) {
      spdlog::warn("[LS] failed to create {} sprite", name_);
      return nullptr;
    }

    sprite_handle_ = il2cpp_gchandle_new(sprite, false);
    if (!sprite_handle_) spdlog::warn("[LS] failed to root {} sprite", name_);
    return sprite_handle_ ? il2cpp_gchandle_get_target(sprite_handle_) : nullptr;
  }

  void Reset()
  {
    if (sprite_handle_) {
      il2cpp_gchandle_free(sprite_handle_);
      sprite_handle_ = nullptr;
    }
    if (texture_handle_) {
      il2cpp_gchandle_free(texture_handle_);
      texture_handle_ = nullptr;
    }
    width_  = 0;
    height_ = 0;
    name_   = "loading asset";
  }

  [[nodiscard]] int32_t Width() const { return width_; }
  [[nodiscard]] int32_t Height() const { return height_; }

private:
  Il2CppGCHandle texture_handle_ = nullptr;
  Il2CppGCHandle sprite_handle_  = nullptr;
  int32_t        width_          = 0;
  int32_t        height_         = 0;
  const char*    name_           = "loading asset";
};

inline RootedImageAsset& LoadingAsset()
{
  static RootedImageAsset asset;
  return asset;
}

inline RootedImageAsset& LogoAsset()
{
  static RootedImageAsset asset;
  return asset;
}

inline RootedImageAsset& CCLogoAsset()
{
  static RootedImageAsset asset;
  return asset;
}

inline void ResetLoadingAssetsForScene()
{
  LoadingAsset().Reset();
  LogoAsset().Reset();
  CCLogoAsset().Reset();
  spdlog::debug("[LS] released previous loading assets for new LoginSequence");
}

inline RootedImageAsset* GetLoadingAsset()
{
  auto& asset = LoadingAsset();
  if (asset.Texture()) return &asset;

  const std::string& path = Config::Get().loader_image;
  if (!path.empty() && std::filesystem::exists(path)) {
    std::ifstream f(path, std::ios::binary);
    if (f.is_open()) {
      std::vector<uint8_t> data(std::istreambuf_iterator<char>(f), {});
      if (!data.empty() && asset.Load(data.data(), data.size(), 1334, 750, "custom loading background")) {
        return &asset;
      }
    }
  }

  return asset.Load(g_embeddedLoadingImage, g_embeddedLoadingImage_SIZE, 1334, 750, "embedded loading background")
             ? &asset
             : nullptr;
}

inline RootedImageAsset* GetLogoAsset()
{
  auto& asset = LogoAsset();
  return (asset.Texture() || asset.Load(g_embeddedLogoImage, g_embeddedLogoImage_SIZE, 600, 828, "mod logo"))
             ? &asset
             : nullptr;
}

inline RootedImageAsset* GetCCLogoAsset()
{
  auto& asset = CCLogoAsset();
  return (asset.Texture()
          || asset.Load(g_embeddedCCLogoImage, g_embeddedCCLogoImage_SIZE, 600, 815, "community logo"))
             ? &asset
             : nullptr;
}

inline void* CreateImageOverlay(const char* name, RootedImageAsset& asset, void* parentTransform, FakeVector2 aMin,
                                FakeVector2 aMax, FakeVector2 pivot, FakeVector2 sd, FakeVector2 ap,
                                bool preserveAspect, bool placeAsFirstSibling)
{
  if (!parentTransform) return nullptr;

  static auto go_h  = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "GameObject");
  static auto rt_h  = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "RectTransform");
  static auto tr_h  = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Transform");
  static auto img_h = il2cpp_get_class_helper("UnityEngine.UI", "UnityEngine.UI", "Image");

  static auto fn_go_ctor = go_h.GetMethodInfoSpecial(".ctor", [](int n, const Il2CppType** p) {
    return n == 1 && p[0]->type == IL2CPP_TYPE_STRING;
  });
  static auto fn_get_tr  = go_h.GetMethodInfo("get_transform");
  static auto fn_setpar  = tr_h.GetMethodInfoSpecial("SetParent", [](int n, const Il2CppType**) { return n == 2; });
  static auto fn_setfst  = tr_h.GetMethodInfo("SetAsFirstSibling");
  static auto fn_addcomp = go_h.GetMethodInfo("AddComponent", 1);
  static auto fn_gc      = go_h.GetMethodInfo("GetComponent", 1);
  if (!fn_go_ctor || !fn_get_tr || !fn_setpar || !fn_addcomp || !fn_gc) return nullptr;

  void* spr = asset.Sprite();
  if (!spr) return nullptr;

  auto* go = il2cpp_object_new(go_h.get_cls());
  if (!go) return nullptr;
  Il2CppGCHandle go_handle = il2cpp_gchandle_new(go, false);
  if (!go_handle) return nullptr;

  void* nameStr   = il2cpp_string_new(name);
  void* goArgs[1] = {nameStr};
  if (!InvokeVoid(fn_go_ctor, go, goArgs, "GameObject.ctor")) {
    il2cpp_gchandle_free(go_handle);
    return nullptr;
  }

  void* tr = InvokeObject(fn_get_tr, go, nullptr, "get_transform");
  if (!tr) {
    il2cpp_gchandle_free(go_handle);
    return nullptr;
  }
  bool  worldStays = false;
  void* parArgs[2] = {FindRootCanvas(parentTransform), &worldStays};
  if (!parArgs[0] || !InvokeVoid(fn_setpar, tr, parArgs, "Transform.SetParent")) {
    il2cpp_gchandle_free(go_handle);
    return nullptr;
  }
  if (placeAsFirstSibling && fn_setfst)
    InvokeVoid(fn_setfst, tr, nullptr, "Transform.SetAsFirstSibling");

  void* imgType   = img_h.GetType();
  if (!imgType) {
    il2cpp_gchandle_free(go_handle);
    return nullptr;
  }
  void* acArgs[1] = {imgType};
  void* imgComp   = InvokeObject(fn_addcomp, go, acArgs, "AddComponent<Image>");
  if (!imgComp) {
    il2cpp_gchandle_free(go_handle);
    return nullptr;
  }

  void* rtType    = rt_h.GetType();
  if (!rtType) {
    il2cpp_gchandle_free(go_handle);
    return nullptr;
  }
  void* rtArgs[1] = {rtType};
  void* rt        = InvokeObject(fn_gc, go, rtArgs, "GetComponent<RectTransform>");
  if (!rt) {
    il2cpp_gchandle_free(go_handle);
    return nullptr;
  }
  SetFullRect(rt, aMin, aMax, pivot, sd, ap);

  if (!ConfigureImageSprite(imgComp, spr, preserveAspect)) {
    il2cpp_gchandle_free(go_handle);
    return nullptr;
  }

  void* result = il2cpp_gchandle_get_target(go_handle);
  il2cpp_gchandle_free(go_handle);
  spdlog::debug("[LS] created {} overlay", name);
  return result;
}

inline void CreateLogoOverlayEx(const char* name, RootedImageAsset* asset, void* parentTransform, void*& outGO,
                                float xSide)
{
  if (outGO) return;
  try {
    if (!asset || !parentTransform) return;

    constexpr float kRefScreenWidth = 1920.0f;
    constexpr float kRefLogoWidth   = 150.0f;
    constexpr float kRefPadX        = 30.0f;
    constexpr float kRefPadY        = 185.0f;

    static auto screen_h = il2cpp_get_class_helper("UnityEngine.CoreModule", "UnityEngine", "Screen");
    static auto fn_sw    = screen_h.GetMethodInfo("get_width");
    static auto fn_sh    = screen_h.GetMethodInfo("get_height");
    float       sw       = (float)(fn_sw ? InvokeInt32(fn_sw, nullptr, 0, "Screen.get_width") : 0);
    float       sh       = (float)(fn_sh ? InvokeInt32(fn_sh, nullptr, 0, "Screen.get_height") : 0);
    if (sw <= 0.0f) sw = 1334.0f;
    if (sh <= 0.0f) sh = 750.0f;

    float scale = (sw / kRefScreenWidth) * Config::Get().loader_logo_scale;

    const int32_t lw = asset->Width();
    const int32_t lh = asset->Height();
    float logoWidth = kRefLogoWidth * scale;
    float logoPixH  = logoWidth * ((lw > 0) ? (float)lh / (float)lw : 1.0f);
    float padX      = kRefPadX * scale;
    float padY      = kRefPadY * scale;

    FakeVector2 aMin, aMax;
    if (xSide < 0.0f) {
      aMin = {padX / sw, padY / sh};
      aMax = {(padX + logoWidth) / sw, (padY + logoPixH) / sh};
    } else {
      aMin = {(sw - padX - logoWidth) / sw, padY / sh};
      aMax = {(sw - padX) / sw, (padY + logoPixH) / sh};
    }

    outGO = CreateImageOverlay(name, *asset, parentTransform, aMin, aMax,
                               {0.5f, 0.5f}, {0.0f, 0.0f}, {0.0f, 0.0f},
                               true, false);
  } catch (...) {}
}

inline void CreateLogoOverlay(void* parentTransform, void*& logoGO)
{
  CreateLogoOverlayEx("STFCModLogo", GetLogoAsset(), parentTransform, logoGO, 1.0f);
}

inline void CreateCCLogoOverlay(void* parentTransform, void*& ccLogoGO)
{
  CreateLogoOverlayEx("STFCCCLogo", GetCCLogoAsset(), parentTransform, ccLogoGO, -1.0f);
}

inline void ApplySpriteToImage(void* imageComp, RootedImageAsset& asset)
{
  if (!imageComp) return;
  void* spr = asset.Sprite();
  if (!spr) return;
  static auto img_h  = il2cpp_get_class_helper("UnityEngine.UI", "UnityEngine.UI", "Image");
  static auto fn_ovr = img_h.GetMethodInfo("set_overrideSprite");
  static auto fn_drt = img_h.GetMethodInfo("SetVerticesDirty");
  void*       sprArgs[1] = {spr};
  InvokeVoid(fn_ovr, imageComp, sprArgs, "Image.set_overrideSprite");
  if (!ConfigureImageSprite(imageComp, spr, false)) return;
  InvokeVoid(fn_drt, imageComp, nullptr, "Graphic.SetVerticesDirty");
}

inline void* CreateBGOverlay(void* parentTransform, RootedImageAsset& asset)
{
  return CreateImageOverlay("STFCModBG", asset, parentTransform,
                            {0.0f, 0.0f}, {1.0f, 1.0f}, {0.5f, 0.5f},
                            {0.0f, 0.0f}, {0.0f, 0.0f}, false,
                            true);
}

} // namespace ls_common
